# Generated by Django 6.0.5 on 2026-05-25 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct emissions'), (2, 'Scope 2 — Purchased electricity'), (3, 'Scope 3 — Value chain')])),
                ('category', models.CharField(choices=[('S1_FUEL_STATIONARY', 'Stationary combustion (fuel)'), ('S1_FUEL_MOBILE', 'Mobile combustion (fleet fuel)'), ('S2_ELECTRICITY', 'Purchased electricity'), ('S3_BUSINESS_TRAVEL_FLIGHT', 'Business travel — flight'), ('S3_BUSINESS_TRAVEL_HOTEL', 'Business travel — hotel'), ('S3_BUSINESS_TRAVEL_GROUND', 'Business travel — ground transport'), ('S3_PROCUREMENT', 'Upstream procurement')], max_length=64)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=128)),
                ('cost_center', models.CharField(blank=True, max_length=128)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity_raw', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit_raw', models.CharField(max_length=32)),
                ('quantity_normalized', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('unit_normalized', models.CharField(default='', max_length=32)),
                ('emission_factor', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=64)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('flagged_reasons', models.JSONField(default=list)),
                ('is_estimated', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('FLAGGED', 'Flagged — needs attention'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('original_values', models.JSONField(default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.datasource')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Record created'), ('EDITED', 'Field edited'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged'), ('LOCKED', 'Locked'), ('NOTE_ADDED', 'Note added')], max_length=16)),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='core.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='core.datasource')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.organization')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.organization'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_status', models.CharField(choices=[('OK', 'Parsed successfully'), ('WARNING', 'Parsed with warnings'), ('ERROR', 'Parse failed')], default='OK', max_length=10)),
                ('parse_errors', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.ingestionbatch')),
            ],
            options={
                'unique_together': {('batch', 'row_number')},
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='core.rawrecord'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'scope'], name='core_emissi_organiz_b87f27_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['organization', 'review_status'], name='core_emissi_organiz_146fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='core_emissi_batch_i_0918bd_idx'),
        ),
    ]
