# Generated by Django 6.0.5 on 2026-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='category',
            field=models.CharField(choices=[('S1_FUEL_STATIONARY', 'Stationary combustion'), ('S1_FUEL_MOBILE', 'Mobile combustion'), ('S2_ELECTRICITY', 'Purchased electricity'), ('S3_BUSINESS_TRAVEL_FLIGHT', 'Business travel - flight'), ('S3_BUSINESS_TRAVEL_HOTEL', 'Business travel - hotel'), ('S3_BUSINESS_TRAVEL_GROUND', 'Business travel - ground'), ('S3_PROCUREMENT', 'Upstream procurement')], max_length=64),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='scope',
            field=models.IntegerField(choices=[(1, 'Scope 1 - Direct emissions'), (2, 'Scope 2 - Purchased electricity'), (3, 'Scope 3 - Value chain')]),
        ),
    ]
